name: Build and deploy Laravel app to Azure Web App - appserviceDojo14-04-2025

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo, sqlsrv, pdo_sqlsrv, openssl

      - name: Install composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Create .env file
        run: |
          echo "APP_NAME=Laravel" >> .env
          echo "APP_ENV=production" >> .env
          echo "APP_DEBUG=false" >> .env
          echo "APP_KEY=${{ secrets.APP_KEY }}" >> .env
          echo "APP_URL=${{ secrets.APP_URL }}" >> .env

          echo "DB_CONNECTION=sqlsrv" >> .env
          echo "DB_HOST=\${DB_HOST}" >> .env
          echo "DB_PORT=1433" >> .env
          echo "DB_DATABASE=\${DB_DATABASE}" >> .env
          echo "DB_USERNAME=\${BD_USERNAME}" >> .env
          echo "DB_PASSWORD=\${BD_PASSWORD}" >> .env

      - name: Set storage permissions
        run: chmod -R 775 storage bootstrap/cache

      - name: Zip artifact for deployment
        run: zip release.zip . -r

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: php-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: php-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8732D61D6DBE476D9CADB85EB165F48B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5E2F3F83A5BB4068AC82C81AA8EFCA37 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3E0413D16B324BD5B0052BA04E3733AA }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'appserviceDojo14-04-2025'
          slot-name: 'Production'
          package: .

      - name: Run Laravel migrations
        run: php artisan migrate --force || echo "Migración ya aplicada o sin cambios"
